spring.application.name=url-shortner
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshorten
spring.datasource.password=Prajjwal24!
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
