spring.application.name=jpa-entities
spring.datasource.url=jdbc:postgresql://localhost:5432/learn
spring.datasource.username=postgres
spring.datasource.password=Prajjwal24!
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update